FROM ubuntu

#Used to disable interactive install for packages[Mainly used for tzdata]
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update

#This is installing timezone data it is used to set the default time to UTC [Mainly used for openjdk8-jre]
RUN apt-get -y install tzdata

#Some necessary packages to install mongoDB,java-jre and rclone
RUN apt-get install -y curl
RUN apt-get install -y unzip
RUN apt-get install -y gnupg
RUN apt-get install -y wget
RUN apt-get install -y sudo

#Installing rclone
RUN curl https://rclone.org/install.sh | sudo bash
RUN apt-get install -y fuse

#systemctl software suite that provides an array of system components for Linux operating systems
#It maybe used to start mongodb
RUN apt-get install -y systemctl

#Installing only Java-Runtime to run java applications[jar files]
RUN apt-get install -y openjdk-8-jre

#MongoDB installation seteps[Refer mongodb installation docs]
RUN wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
RUN echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
RUN apt-get update
RUN apt-get install -y mongodb-org

#MongoDB operates at "/data/db" by defaults and these folders aren't created by default
#We are creating the folder and taking ownership[chown... command] so that mongodb can write to it
RUN mkdir -p /data/db
RUN chmod 777 /data/db

#Making datacopy directory
RUN mkdir -p /data-copy

#Creating some Directories to copy jar files and execute it from this folder
RUN mkdir /app

#Copy config files
COPY rclone.conf /
RUN chmod +x /rclone.conf

#[Optional]Created a general shell and aquired ownership script which can be used to run taks
COPY start.sh /app/
RUN chmod +x /app/start.sh

#Copying the jar file generated by the gradle and aquiring its ownership
COPY ./build/libs/demo*all.jar /app/demo.jar
RUN chmod +x /app/demo.jar

#Setting the work directory to start the copied jar file
WORKDIR /app

#CMD statements are executed at run time
#This statement starts the mongodb server and binds to 0.0.0.0[localhost] and starts the ktor application
#CMD mongod --bind_ip 0. 0.0.0 & java -server -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:InitialRAMFraction=2 -XX:MinRAMFraction=2 -XX:MaxRAMFraction=2 -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -jar demo.jar
